name: k_chart
description: A Flutter K Chart.
version: 0.6.1
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
